version: "3.8"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from .env file

  db:
    image: postgres
    restart: always
    env_file:
      - .env  # Load PostgreSQL credentials from .env file
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
